CREATE SCHEMA `messages` ;

CREATE  TABLE `messages`.`USERS` (
  `idUSERS` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(45) NOT NULL ,
  `STATUS` VARCHAR(45) NOT NULL ,
  `ROLE` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`idUSERS`) );

CREATE  TABLE `messages`.`TOPICS` (
  `idTOPICS` INT NOT NULL AUTO_INCREMENT,
  `DENUMIRE` VARCHAR(150) NOT NULL ,
  `TOPICNAME` VARCHAR(150) NOT NULL ,
  `INSERTDATE` DATETIME NULL ,
  PRIMARY KEY (`idTOPICS`) );

CREATE  TABLE `messages`.`MESSAGES` (
  `idMESSAGES` INT NOT NULL AUTO_INCREMENT,
  `DENUMIRE` VARCHAR(150) NOT NULL ,
  `DESCRIERE` VARCHAR(450) NOT NULL ,
  `FK_ID_TOPIC` INT NOT NULL ,
  `LASTMODIFIED` DATETIME NULL ,
  PRIMARY KEY (`idMESSAGES`) );

CREATE  TABLE `messages`.`NOTIFICATIONS` (
  `idNOTIFICATIONS` INT NOT NULL AUTO_INCREMENT,
  `FK_ID_USER` INT NOT NULL ,
  `FK_ID_TOPIC` INT NOT NULL ,
  `MSG_NR` INT NOT NULL DEFAULT 5,
  `STATUS` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`idNOTIFICATIONS`) );


INSERT INTO `messages`.`USERS` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('daniel', 'daniel', 'admin');
INSERT INTO `messages`.`USERS` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('paul', 'paul', 'user');
INSERT INTO `messages`.`USERS` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('marius', 'marius', 'user');

INSERT INTO `messages`.`TOPICS` (`DENUMIRE`, `TOPICNAME`, `INSERTDATE`) VALUES ('/topic1', 'Topic 1',NOW());
INSERT INTO `messages`.`TOPICS` (`DENUMIRE`, `TOPICNAME`, `INSERTDATE`) VALUES ('/topic2', 'Topic 2',NOW());  

INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj1','mesaj1',1,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj2','mesaj2',1,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj3','mesaj3',2,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj4','mesaj4',1,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj5','mesaj5',1,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj6','mesaj6',2,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj7','mesaj7',1,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj8','mesaj8',1,NOW());
INSERT INTO `messages`.`MESSAGES` (`DENUMIRE`,`DESCRIERE`,`FK_ID_TOPIC`,`LASTMODIFIED`)  VALUES ('mesaj9','mesaj9',2,NOW());

INSERT INTO `messages`.`NOTIFICATIONS` (`FK_ID_USER`,`FK_ID_TOPIC`,`MSG_NR`,`STATUS`) VALUES (1,1,5,'pending');
INSERT INTO `messages`.`NOTIFICATIONS` (`FK_ID_USER`,`FK_ID_TOPIC`,`MSG_NR`,`STATUS`) VALUES (2,1,5,'pending');
INSERT INTO `messages`.`NOTIFICATIONS` (`FK_ID_USER`,`FK_ID_TOPIC`,`MSG_NR`,`STATUS`) VALUES (3,1,5,'pending');












