CREATE SCHEMA `messages` ;

CREATE  TABLE `messages`.`USERS` (
  `idUSERS` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(45) NOT NULL ,
  `ROLE` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`idUSERS`) );

CREATE  TABLE `messages`.`TOPICS` (
  `idTOPICS` INT NOT NULL AUTO_INCREMENT,
  `DENUMIRE` VARCHAR(150) NOT NULL ,
  `TOPICNAME` VARCHAR(150) NOT NULL ,
  `INSERTDATE` DATETIME NULL ,
  PRIMARY KEY (`idTOPICS`) );

CREATE  TABLE `messages`.`MESSAGES` (
  `idMESSAGES` INT NOT NULL AUTO_INCREMENT,
  `DENUMIRE` VARCHAR(150) NOT NULL ,
  `DESCRIERE` VARCHAR(450) NOT NULL ,
  `FK_ID_TOPIC` INT NOT NULL ,
  `LASTMODIFIED` DATETIME NULL ,
  PRIMARY KEY (`idMESSAGES`) );

CREATE  TABLE `messages`.`NOTIFICATIONS` (
  `idNOTIFICATIONS` INT NOT NULL AUTO_INCREMENT,
  `FK_ID_USER` INT NOT NULL ,
  `FK_ID_TOPIC` INT NOT NULL ,
  `MSG_NR` INT NOT NULL DEFAULT 5,
  `STATUS` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`idNOTIFICATIONS`) );


INSERT INTO `messages`.`USERS` (`USERNAME`, `PASSWORD`, `SESSIONID`) VALUES ('daniel', 'daniel', '222aads');
INSERT INTO `messages`.`USERS` (`USERNAME`, `PASSWORD`, `SESSIONID`) VALUES ('paul', 'paul', '111aads');
INSERT INTO `messages`.`USERS` (`USERNAME`, `PASSWORD`, `SESSIONID`) VALUES ('marius', 'marius', '333aads');

INSERT INTO `messages`.`TOPICS` (`DENUMIRE`, `TOPICNAME`, `INSERTDATE`) VALUES ('/topic1', 'Topic 1',NOW()); 

INSERT INTO `messages`.`MESSAGES` (`DESCRIERE`,`FK_ID_TOPIC`)  VALUES ('mesaj1 pentru topic fk_id=1',1);
INSERT INTO `messages`.`MESSAGES` (`DESCRIERE`,`FK_ID_TOPIC`)  VALUES ('mesaj2 pentru topic fk_id=1',1);
INSERT INTO `messages`.`MESSAGES` (`DESCRIERE`,`FK_ID_TOPIC`)  VALUES ('mesaj3 pentru topic fk_id=1',1);

INSERT INTO `messages`.`NOTIFICATIONS` (`FK_ID_USER`,`RESOURCE_INFO`,`FK_ID_TOPIC`,`MSG_NR`,`STATUS`) VALUES (1,1,5,'pending');
INSERT INTO `messages`.`NOTIFICATIONS` (`FK_ID_USER`,`RESOURCE_INFO`,`FK_ID_TOPIC`,`MSG_NR`,`STATUS`) VALUES (2,1,5,'pending');
INSERT INTO `messages`.`NOTIFICATIONS` (`FK_ID_USER`,`RESOURCE_INFO`,`FK_ID_TOPIC`,`MSG_NR`,`STATUS`) VALUES (3,1,5,'pending');













